### ISSUE TITLE
non-issue, just wanted to thank the maintainers

### ISSUE THREAD

**Issue by rs-sathya** [Innervate/s3-sns-lambda-replay#2]
The tool just works, and you saved me so much time!

Really appreciate this little tool. It helped me replay events after a lambda function OOM failure we didn't catch caused long-term missed processing.

Thank you!!

**Comment by rsyvarth** [comment]
Glad to hear it was helpful! Please let us know if there is anything we can do to make it more useful for you :)

**Comment by rs-sathya** [comment]
I did drop a few issues for you, as I had to make some modifications to fit some use-cases that I believe might be common for users of this tool :)

Thanks again!
